# Generated by Django 4.0.5 on 2023-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_testenv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('xpath', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=20)),
                ('screen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('env_id', models.IntegerField()),
            ],
        ),
    ]
