# Generated by Django 4.0.5 on 2023-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_pointstep_testpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenv',
            name='name',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
